<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Diego Villalba (Applied Research Candidate)">
<meta name="dcterms.date" content="2026-06-26">

<title>2. Data Distribution &amp; Sampler Correction – ReportCXR</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-edad393940abb5f3c6973fe701e515d2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e9614ef202455b86b71b0557e717d80d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ReportCXR</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-technical-report" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Technical Report</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-technical-report">    
        <li>
    <a class="dropdown-item" href="../report/01_introduction.html">
 <span class="dropdown-text">1. Introduction &amp; Strategic Thesis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../report/02_data.html">
 <span class="dropdown-text">2. Data Distribution &amp; Sampler</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../report/03_model_training.html">
 <span class="dropdown-text">3. Model &amp; QLoRA Config</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../report/04_evaluation.html">
 <span class="dropdown-text">4. Evaluation &amp; Metric Pivot</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../report/05_inference_conditioning.html">
 <span class="dropdown-text">5. Inference Conditioning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../report/06_domain_shift.html">
 <span class="dropdown-text">6. Domain Shift Audit Protocol</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../report/07_production_scaling.html">
 <span class="dropdown-text">7. Production Scaling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-code-documentation" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Code Documentation</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-code-documentation">    
        <li>
    <a class="dropdown-item" href="../doc/architecture.html">
 <span class="dropdown-text">Architecture Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../doc/data_pipeline.html">
 <span class="dropdown-text">Data Pipeline</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../doc/training_pipeline.html">
 <span class="dropdown-text">Model &amp; Training</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../doc/evaluation_modules.html">
 <span class="dropdown-text">Evaluation Modules</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../doc/domain_shift_modules.html">
 <span class="dropdown-text">Domain Shift Audit</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../doc/demo_deployment.html">
 <span class="dropdown-text">Demo &amp; Deployment</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-notebooks" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Notebooks</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-notebooks">    
        <li>
    <a class="dropdown-item" href="../notebooks/01_eda.html">
 <span class="dropdown-text">01: Exploratory Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/02_baseline_zero_shot.html">
 <span class="dropdown-text">02: Zero-Shot Baseline</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/03_train_local.html">
 <span class="dropdown-text">03: Training (Local)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/03_train_kaggle.html">
 <span class="dropdown-text">03: Training (Kaggle)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/04_eval_and_figures.html">
 <span class="dropdown-text">04: Evaluation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/05_rag_retrieval.html">
 <span class="dropdown-text">05: RAG Retrieval</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notebooks/06_association_rules.html">
 <span class="dropdown-text">06: Association Rules</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#dataset-loading-integrity-audit" id="toc-dataset-loading-integrity-audit" class="nav-link active" data-scroll-target="#dataset-loading-integrity-audit">1. Dataset Loading &amp; Integrity Audit</a>
  <ul class="collapse">
  <li><a href="#projection-coverage" id="toc-projection-coverage" class="nav-link" data-scroll-target="#projection-coverage">1.1 Projection Coverage</a></li>
  <li><a href="#null-counts-in-raw-reports" id="toc-null-counts-in-raw-reports" class="nav-link" data-scroll-target="#null-counts-in-raw-reports">1.2 Null Counts in Raw Reports</a></li>
  <li><a href="#usable-study-count" id="toc-usable-study-count" class="nav-link" data-scroll-target="#usable-study-count">1.3 Usable Study Count</a></li>
  </ul></li>
  <li><a href="#chexbert-labeling" id="toc-chexbert-labeling" class="nav-link" data-scroll-target="#chexbert-labeling">2. CheXbert Labeling</a>
  <ul class="collapse">
  <li><a href="#positive-counts-per-label" id="toc-positive-counts-per-label" class="nav-link" data-scroll-target="#positive-counts-per-label">2.1 Positive Counts per Label</a></li>
  </ul></li>
  <li><a href="#dataset-distribution-concentration" id="toc-dataset-distribution-concentration" class="nav-link" data-scroll-target="#dataset-distribution-concentration">3. Dataset Distribution &amp; Concentration</a>
  <ul class="collapse">
  <li><a href="#dataset-concentration-metrics" id="toc-dataset-concentration-metrics" class="nav-link" data-scroll-target="#dataset-concentration-metrics">3.1 Dataset Concentration Metrics</a></li>
  <li><a href="#tail-mass" id="toc-tail-mass" class="nav-link" data-scroll-target="#tail-mass">3.2 Tail Mass</a></li>
  </ul></li>
  <li><a href="#hierarchical-clustering-label-associations" id="toc-hierarchical-clustering-label-associations" class="nav-link" data-scroll-target="#hierarchical-clustering-label-associations">4. Hierarchical Clustering &amp; Label Associations</a>
  <ul class="collapse">
  <li><a href="#hierarchical-agglomerative-clustering-implementation" id="toc-hierarchical-agglomerative-clustering-implementation" class="nav-link" data-scroll-target="#hierarchical-agglomerative-clustering-implementation">4.1 Hierarchical Agglomerative Clustering Implementation</a></li>
  <li><a href="#top-conditional-co-occurrence-pairs" id="toc-top-conditional-co-occurrence-pairs" class="nav-link" data-scroll-target="#top-conditional-co-occurrence-pairs">4.2 Top Conditional Co-occurrence Pairs</a></li>
  </ul></li>
  <li><a href="#association-rules-mining" id="toc-association-rules-mining" class="nav-link" data-scroll-target="#association-rules-mining">5. Association Rules Mining</a></li>
  <li><a href="#importance-sampling-sampler-correction" id="toc-importance-sampling-sampler-correction" class="nav-link" data-scroll-target="#importance-sampling-sampler-correction">6. Importance Sampling &amp; Sampler Correction</a>
  <ul class="collapse">
  <li><a href="#ess-based-sampler-settings-v4" id="toc-ess-based-sampler-settings-v4" class="nav-link" data-scroll-target="#ess-based-sampler-settings-v4">6.1 ESS-Based Sampler Settings (v4)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">2. Data Distribution &amp; Sampler Correction</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Diego Villalba (Applied Research Candidate) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="section-summary-non-technical" class="level5 non-technical-summary">
<h5 class="anchored" data-anchor-id="section-summary-non-technical">Section Summary (Non-Technical)</h5>
<p>This section explains how we handle the huge imbalance in clinical data. Most X-rays are completely normal, meaning that an AI trained on this data would quickly learn to default to predicting “normal” to get easy high scores. We solve this by calculating mathematical weights for each study. When the AI trains, it is shown rare pathologies more frequently and normal X-rays less frequently. This forces the model to actually learn the signatures of rare diseases rather than taking lazy shortcuts.</p>
</section>
<section id="dataset-loading-integrity-audit" class="level2">
<h2 class="anchored" data-anchor-id="dataset-loading-integrity-audit">1. Dataset Loading &amp; Integrity Audit</h2>
<p>The Indiana University Chest X-ray (IU CXR) dataset consists of two raw CSV files:</p>
<ul>
<li><strong><code>indiana_reports.csv</code></strong> — 3,851 rows × 8 columns (<code>uid</code>, <code>MeSH</code>, <code>Problems</code>, <code>image</code>, <code>indication</code>, <code>comparison</code>, <code>findings</code>, <code>impression</code>)</li>
<li><strong><code>indiana_projections.csv</code></strong> — 7,466 rows × 3 columns (<code>uid</code>, <code>filename</code>, <code>projection</code>)</li>
</ul>
<p>Each study (<code>uid</code>) links to one or two image projections. Reports and projections are joined on <code>uid</code> to produce a per-study dataframe (one row per study, with <code>frontal</code> and <code>lateral</code> image lists as columns).</p>
<section id="projection-coverage" class="level3">
<h3 class="anchored" data-anchor-id="projection-coverage">1.1 Projection Coverage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Projections per study</th>
<th>Studies</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>446</td>
</tr>
<tr class="even">
<td>2</td>
<td>3,210</td>
</tr>
<tr class="odd">
<td>3</td>
<td>181</td>
</tr>
<tr class="even">
<td>4</td>
<td>13</td>
</tr>
<tr class="odd">
<td>5</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Of the 3,851 studies: <strong>3,689 have at least one frontal image</strong> and <strong>3,550 have a lateral image</strong>. The 162 studies lacking a frontal view are still retained in the join — the model always receives the frontal image at training time; if unavailable, the study is skipped.</p>
</section>
<section id="null-counts-in-raw-reports" class="level3">
<h3 class="anchored" data-anchor-id="null-counts-in-raw-reports">1.2 Null Counts in Raw Reports</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Column</th>
<th>Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>indication</code></td>
<td>86</td>
</tr>
<tr class="even">
<td><code>comparison</code></td>
<td>1,166</td>
</tr>
<tr class="odd">
<td><code>findings</code></td>
<td>514</td>
</tr>
<tr class="even">
<td><code>impression</code></td>
<td>31</td>
</tr>
</tbody>
</table>
</section>
<section id="usable-study-count" class="level3">
<h3 class="anchored" data-anchor-id="usable-study-count">1.3 Usable Study Count</h3>
<p>Studies without a <code>findings</code> text cannot be used as generation targets and are dropped:</p>
<p><span class="math display">\[N_{\text{raw}} = 3{,}851 \xrightarrow{\text{drop empty findings}} N_{\text{usable}} = 3{,}337\]</span></p>
<p>This <strong>3,337-study corpus</strong> is the basis for all subsequent analysis, CheXbert labeling, and the train/test split.</p>
<hr>
</section>
</section>
<section id="chexbert-labeling" class="level2">
<h2 class="anchored" data-anchor-id="chexbert-labeling">2. CheXbert Labeling</h2>
<p>Each study’s <code>findings</code> text is passed through <strong>CheXbert</strong> <span class="citation" data-cites="chen2024chexagent">(<a href="#ref-chen2024chexagent" role="doc-biblioref">Chen et al. 2024</a>)</span>, a BERT-based classifier that extracts a 14-dimensional binary label vector. The <code>uncertain_policy</code> is set to <code>positive</code> (uncertain mentions are treated as present).</p>
<p>Results are cached to <code>data/processed/chexbert_labels.parquet</code> after the first run (~10–20 min on CPU).</p>
<section id="positive-counts-per-label" class="level3">
<h3 class="anchored" data-anchor-id="positive-counts-per-label">2.1 Positive Counts per Label</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Label</th>
<th>Positive studies</th>
<th>Prevalence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No Finding</td>
<td>1,293</td>
<td><strong>38.7%</strong></td>
</tr>
<tr class="even">
<td>Lung Opacity</td>
<td>450</td>
<td>13.5%</td>
</tr>
<tr class="odd">
<td>Cardiomegaly</td>
<td>414</td>
<td>12.4%</td>
</tr>
<tr class="even">
<td>Enlarged Cardiomediastinum</td>
<td>249</td>
<td>7.5%</td>
</tr>
<tr class="odd">
<td>Atelectasis</td>
<td>224</td>
<td>6.7%</td>
</tr>
<tr class="even">
<td>Support Devices</td>
<td>153</td>
<td>4.6%</td>
</tr>
<tr class="odd">
<td>Lung Lesion</td>
<td>134</td>
<td>4.0%</td>
</tr>
<tr class="even">
<td>Fracture</td>
<td>121</td>
<td>3.6%</td>
</tr>
<tr class="odd">
<td>Pleural Effusion</td>
<td>105</td>
<td>3.1%</td>
</tr>
<tr class="even">
<td>Pleural Other</td>
<td>49</td>
<td>1.5%</td>
</tr>
<tr class="odd">
<td>Edema</td>
<td>44</td>
<td>1.3%</td>
</tr>
<tr class="even">
<td>Pneumonia</td>
<td>30</td>
<td>0.9%</td>
</tr>
<tr class="odd">
<td>Consolidation</td>
<td>25</td>
<td>0.7%</td>
</tr>
<tr class="even">
<td>Pneumothorax</td>
<td>17</td>
<td>0.5%</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="dataset-distribution-concentration" class="level2">
<h2 class="anchored" data-anchor-id="dataset-distribution-concentration">3. Dataset Distribution &amp; Concentration</h2>
<div id="fig-dataset-dist" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dataset-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-dataset-dist" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-prevalences" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-prevalences-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../reports/figures/label_prevalences.png" class="lightbox" data-gallery="fig-dataset-dist" title="Figure&nbsp;1&nbsp;(a): Label Prevalences in the IU CXR Dataset"><img src="../reports/figures/label_prevalences.png" class="img-fluid figure-img" data-ref-parent="fig-dataset-dist"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-prevalences-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Label Prevalences in the IU CXR Dataset
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-dataset-dist" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-cooccurrence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-cooccurrence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../reports/figures/cooccurrence_matrix.png" class="lightbox" data-gallery="fig-dataset-dist" title="Figure&nbsp;1&nbsp;(b): Pathology Co-occurrence Matrix"><img src="../reports/figures/cooccurrence_matrix.png" class="img-fluid figure-img" data-ref-parent="fig-dataset-dist"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-cooccurrence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Pathology Co-occurrence Matrix
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-dataset-dist" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-ess" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ess-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../reports/figures/class_ess.png" class="lightbox" data-gallery="fig-dataset-dist" title="Figure&nbsp;1&nbsp;(c): Effective Sample Size (ESS) per Clinical Label"><img src="../reports/figures/class_ess.png" class="img-fluid figure-img" data-ref-parent="fig-dataset-dist"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ess-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Effective Sample Size (ESS) per Clinical Label
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dataset-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Clinical data distributions and label statistics.
</figcaption>
</figure>
</div>
<p>The severe class imbalance is illustrated in <a href="#fig-prevalences" class="quarto-xref">Figure&nbsp;1 (a)</a> and <a href="#fig-cooccurrence" class="quarto-xref">Figure&nbsp;1 (b)</a>. Nine of the 14 labels have prevalence below 5% (highlighted in red in <a href="#fig-prevalences" class="quarto-xref">Figure&nbsp;1 (a)</a>).</p>
<section id="dataset-concentration-metrics" class="level3">
<h3 class="anchored" data-anchor-id="dataset-concentration-metrics">3.1 Dataset Concentration Metrics</h3>
<p>To quantify how unequally the label mass is distributed, we compute Shannon entropy and effective number of labels:</p>
<p><span class="math display">\[H = -\sum_{l} \hat{p}_l \log \hat{p}_l = 2.005 \text{ nats}\]</span></p>
<p><span class="math display">\[K_{\text{eff}} = e^H = 7.42 \quad (\text{out of 14})\]</span></p>
<p>A uniform 14-label distribution would give <span class="math inline">\(K_{\text{eff}} = 14\)</span>. A value of <strong>7.42</strong> means the dataset behaves as if only ~7 labels exist at equal prevalence — the remaining label mass is dominated by <code>No Finding</code>, <code>Lung Opacity</code>, and <code>Cardiomegaly</code>.</p>
</section>
<section id="tail-mass" class="level3">
<h3 class="anchored" data-anchor-id="tail-mass">3.2 Tail Mass</h3>
<p>We define the “tail” as studies whose only positive labels have prevalence &lt; 5%. These studies carry signal for the rarest pathologies but receive almost no gradient under uniform sampling:</p>
<p><span class="math display">\[\text{Tail mass} = 8.2\% \approx 274 \text{ studies}\]</span></p>
<p>These 274 studies are the ones the importance-weighted sampler is most critical for — they are the first to be de-prioritized under uniform sampling.</p>
<hr>
</section>
</section>
<section id="hierarchical-clustering-label-associations" class="level2">
<h2 class="anchored" data-anchor-id="hierarchical-clustering-label-associations">4. Hierarchical Clustering &amp; Label Associations</h2>
<p>To understand how clinical findings co-occur and group together, we performed hierarchical agglomerative clustering on the binary CheXbert label vectors from the training set.</p>
<section id="hierarchical-agglomerative-clustering-implementation" class="level3">
<h3 class="anchored" data-anchor-id="hierarchical-agglomerative-clustering-implementation">4.1 Hierarchical Agglomerative Clustering Implementation</h3>
<p>Each label <span class="math inline">\(l \in L\)</span> is represented as a boolean occurrence vector <span class="math inline">\(v_l \in \{0, 1\}^N\)</span> over the <span class="math inline">\(N = 3{,}337\)</span> studies. We define the pairwise distance between label occurrence vectors using the Jaccard distance metric to measure the relative co-occurrence similarity:</p>
<p><span class="math display">\[d(A, B) = 1 - \frac{|A \cap B|}{|A \cup B|} = 1 - \frac{\sum_{i=1}^N (L_{i, A} \wedge L_{i, B})}{\sum_{i=1}^N (L_{i, A} \vee L_{i, B})}\]</span></p>
<p>The condensed distance matrix was computed via SciPy’s <code>pdist</code>. We then performed agglomerative clustering via the average linkage method:</p>
<p><span class="math display">\[d(u, v) = \sum_{i \in u, j \in v} \frac{d(i, j)}{|u||v|}\]</span></p>
<p>The clustering tree was visualized as a dendrogram (see <a href="#fig-dendrogram" class="quarto-xref">Figure&nbsp;2 (a)</a>), with the cluster color threshold set at <span class="math inline">\(0.7 \times \max(Z[:, 2])\)</span> to group labels into distinct clinical families.</p>
<div id="fig-clustering-results" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clustering-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-clustering-results" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-dendrogram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-dendrogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../reports/figures/label_dendrogram.png" class="lightbox" data-gallery="fig-clustering-results" title="Figure&nbsp;2&nbsp;(a): Label Hierarchical Clustering Dendrogram"><img src="../reports/figures/label_dendrogram.png" class="img-fluid figure-img" data-ref-parent="fig-clustering-results"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-dendrogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Label Hierarchical Clustering Dendrogram
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-clustering-results" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-assoc-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-assoc-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../reports/figures/assoc_rules_heatmap.png" class="lightbox" data-gallery="fig-clustering-results" title="Figure&nbsp;2&nbsp;(b): Pairwise Association Rules Heatmap"><img src="../reports/figures/assoc_rules_heatmap.png" class="img-fluid figure-img" data-ref-parent="fig-clustering-results"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-assoc-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Pairwise Association Rules Heatmap
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clustering-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Clustering and co-occurrence analysis.
</figcaption>
</figure>
</div>
<p>The dendrogram in <a href="#fig-dendrogram" class="quarto-xref">Figure&nbsp;2 (a)</a> reveals distinct clinical syndromes that align with medical logic:</p>
<ol type="1">
<li><strong>Cardiac Cluster</strong>: Cardiomegaly, Edema, and Enlarged Cardiomediastinum group closely together, reflecting congestive heart failure progression.</li>
<li><strong>Infection/Airspace Cluster</strong>: Pneumonia and Consolidation form a tight cluster, indicating airspace disease.</li>
<li><strong>Pleural Cluster</strong>: Pleural Effusion and Pleural Other group together, showing pleural space pathology.</li>
</ol>
</section>
<section id="top-conditional-co-occurrence-pairs" class="level3">
<h3 class="anchored" data-anchor-id="top-conditional-co-occurrence-pairs">4.2 Top Conditional Co-occurrence Pairs</h3>
<p>Before mining directional rules, the raw conditional co-occurrence matrix surfaces the strongest pairwise associations:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Given (row)</th>
<th>Then (column)</th>
<th>P(col | row)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lung Opacity</td>
<td>Pneumonia</td>
<td>0.633</td>
</tr>
<tr class="even">
<td>Cardiomegaly</td>
<td>Edema</td>
<td>0.614</td>
</tr>
<tr class="odd">
<td>Lung Opacity</td>
<td>Atelectasis</td>
<td>0.540</td>
</tr>
<tr class="even">
<td>Lung Opacity</td>
<td>Consolidation</td>
<td>0.520</td>
</tr>
<tr class="odd">
<td>Lung Opacity</td>
<td>Pleural Effusion</td>
<td>0.448</td>
</tr>
<tr class="even">
<td>Lung Opacity</td>
<td>Edema</td>
<td>0.386</td>
</tr>
<tr class="odd">
<td>Lung Opacity</td>
<td>Pleural Other</td>
<td>0.367</td>
</tr>
<tr class="even">
<td>Cardiomegaly</td>
<td>Pleural Effusion</td>
<td>0.333</td>
</tr>
<tr class="odd">
<td>Cardiomegaly</td>
<td>Enlarged Cardiomediastinum</td>
<td>0.297</td>
</tr>
<tr class="even">
<td>Pleural Effusion</td>
<td>Edema</td>
<td>0.295</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="association-rules-mining" class="level2">
<h2 class="anchored" data-anchor-id="association-rules-mining">5. Association Rules Mining</h2>
<p>This co-occurrence structure confirms that X-ray findings do not occur independently. To mine directional relationships between findings, we implemented association rules mining over the binary label matrix. <code>No Finding</code> is excluded from all rule mining — it is a logical complement label, not a pathology. This yields 90 directional candidate rules across 13 pathology labels.</p>
<p>For each candidate pair of pathologies <span class="math inline">\(A \rightarrow B\)</span>, we compute:</p>
<ol type="1">
<li><strong>Support</strong>: The joint prevalence of both findings in the dataset: <span class="math display">\[\text{Support}(A \rightarrow B) = P(A \wedge B) = \frac{\sum_{i=1}^N L_{i, A} L_{i, B}}{N}\]</span></li>
<li><strong>Confidence</strong>: The conditional probability of consequent <span class="math inline">\(B\)</span> given antecedent <span class="math inline">\(A\)</span>: <span class="math display">\[\text{Confidence}(A \rightarrow B) = P(B \mid A) = \frac{P(A \wedge B)}{P(A)} = \frac{\sum_{i=1}^N L_{i, A} L_{i, B}}{\sum_{i=1}^N L_{i, A}}\]</span></li>
<li><strong>Lift</strong>: The ratio of confidence to the baseline prevalence of <span class="math inline">\(B\)</span>. A lift greater than 1.0 indicates a positive clinical co-occurrence beyond random chance: <span class="math display">\[\text{Lift}(A \rightarrow B) = \frac{P(B \mid A)}{P(B)} = \frac{N \sum_{i=1}^N L_{i, A} L_{i, B}}{\left(\sum_{i=1}^N L_{i, A}\right) \left(\sum_{i=1}^N L_{i, B}\right)}\]</span></li>
</ol>
<p>We mined <strong>90 total directional rules</strong> across 13 pathology labels (excluding <code>No Finding</code>). Filtering at <strong>confidence <span class="math inline">\(\ge 0.25\)</span></strong> and <strong>lift <span class="math inline">\(\ge 1.5\)</span></strong> yields <strong>12 clinically significant rules</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Antecedent (<span class="math inline">\(A\)</span>)</th>
<th>Consequent (<span class="math inline">\(B\)</span>)</th>
<th>Support</th>
<th>Confidence</th>
<th>Lift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Edema</strong></td>
<td>Pleural Effusion</td>
<td><span class="math inline">\(0.0039\)</span></td>
<td><span class="math inline">\(0.2955\)</span></td>
<td><span class="math inline">\(9.3898\)</span></td>
</tr>
<tr class="even">
<td><strong>Edema</strong></td>
<td>Cardiomegaly</td>
<td><span class="math inline">\(0.0081\)</span></td>
<td><span class="math inline">\(0.6136\)</span></td>
<td><span class="math inline">\(4.9461\)</span></td>
</tr>
<tr class="odd">
<td><strong>Atelectasis</strong></td>
<td>Lung Opacity</td>
<td><span class="math inline">\(0.0363\)</span></td>
<td><span class="math inline">\(0.5402\)</span></td>
<td><span class="math inline">\(4.0057\)</span></td>
</tr>
<tr class="even">
<td><strong>Lung Opacity</strong></td>
<td>Atelectasis</td>
<td><span class="math inline">\(0.0363\)</span></td>
<td><span class="math inline">\(0.2689\)</span></td>
<td><span class="math inline">\(4.0057\)</span></td>
</tr>
<tr class="odd">
<td><strong>Pleural Effusion</strong></td>
<td>Lung Opacity</td>
<td><span class="math inline">\(0.0141\)</span></td>
<td><span class="math inline">\(0.4476\)</span></td>
<td><span class="math inline">\(3.3193\)</span></td>
</tr>
<tr class="even">
<td><strong>Edema</strong></td>
<td>Lung Opacity</td>
<td><span class="math inline">\(0.0051\)</span></td>
<td><span class="math inline">\(0.3864\)</span></td>
<td><span class="math inline">\(2.8651\)</span></td>
</tr>
<tr class="odd">
<td><strong>Pleural Other</strong></td>
<td>Lung Opacity</td>
<td><span class="math inline">\(0.0054\)</span></td>
<td><span class="math inline">\(0.3673\)</span></td>
<td><span class="math inline">\(2.7241\)</span></td>
</tr>
<tr class="even">
<td><strong>Pleural Effusion</strong></td>
<td>Cardiomegaly</td>
<td><span class="math inline">\(0.0105\)</span></td>
<td><span class="math inline">\(0.3333\)</span></td>
<td><span class="math inline">\(2.6868\)</span></td>
</tr>
<tr class="odd">
<td><strong>Enlarged Cardiomediastinum</strong></td>
<td>Cardiomegaly</td>
<td><span class="math inline">\(0.0222\)</span></td>
<td><span class="math inline">\(0.2972\)</span></td>
<td><span class="math inline">\(2.3955\)</span></td>
</tr>
<tr class="even">
<td><strong>Pleural Other</strong></td>
<td>Cardiomegaly</td>
<td><span class="math inline">\(0.0039\)</span></td>
<td><span class="math inline">\(0.2653\)</span></td>
<td><span class="math inline">\(2.1385\)</span></td>
</tr>
<tr class="odd">
<td><strong>Enlarged Cardiomediastinum</strong></td>
<td>Lung Opacity</td>
<td><span class="math inline">\(0.0198\)</span></td>
<td><span class="math inline">\(0.2651\)</span></td>
<td><span class="math inline">\(1.9656\)</span></td>
</tr>
<tr class="even">
<td><strong>Support Devices</strong></td>
<td>Lung Opacity</td>
<td><span class="math inline">\(0.0117\)</span></td>
<td><span class="math inline">\(0.2549\)</span></td>
<td><span class="math inline">\(1.8902\)</span></td>
</tr>
</tbody>
</table>
<p>These 12 rules (visualized in <a href="#fig-assoc-heatmap" class="quarto-xref">Figure&nbsp;2 (b)</a>) represent highly strong, non-trivial clinical dependencies. For example: Edema has a 61.4% conditional probability of co-occurring with Cardiomegaly (<span class="math inline">\(\text{lift}=4.95\)</span>), and is 9.39× more likely to co-occur with Pleural Effusion than a study drawn at random.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>EDA vs.&nbsp;inference thresholds</strong>: The EDA strong-rules table above uses lift ≥ 1.5 for display purposes. The runtime inference conditioner in Section 5 uses a slightly more permissive lift ≥ 1.2 threshold to maximize recall of rare associations at inference time. All 12 rules above also satisfy the inference threshold.</p>
</div>
</div>
<p>This motivates injecting these conditional probabilities into the prompting pipeline at test time: if a clinical indication triggers antecedent <span class="math inline">\(A\)</span>, we supply the conditional probability of consequent <span class="math inline">\(B\)</span> as a soft prior context hint (see <a href="../report/05_inference_conditioning.html">Section 5 — Inference Conditioning</a>).</p>
<hr>
</section>
<section id="importance-sampling-sampler-correction" class="level2">
<h2 class="anchored" data-anchor-id="importance-sampling-sampler-correction">6. Importance Sampling &amp; Sampler Correction</h2>
<p>To prevent the model from collapsing to the majority class and simply predicting “normal” for all patients, we implement a <code>WeightedRandomSampler</code>. For each study <span class="math inline">\(j\)</span>, we compute an importance weight <span class="math inline">\(w_j\)</span> based on the target prevalences specified in <code>params.yaml</code>:</p>
<p><span class="math display">\[w_j = \text{clip}\left( \left( \prod_{l \in L_j} \frac{p_{\text{target}}(l)}{p_{\text{dataset}}(l)} \right)^{\frac{1}{|L_j|}}, \text{clip\_val} \right)\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(L_j\)</span> is the set of positive pathologies present in study <span class="math inline">\(j\)</span>.</li>
<li><span class="math inline">\(p_{\text{target}}(l)\)</span> is the user-specified target prevalence for pathology <span class="math inline">\(l\)</span>.</li>
<li><span class="math inline">\(p_{\text{dataset}}(l)\)</span> is the empirical prevalence of pathology <span class="math inline">\(l\)</span> in the training set.</li>
<li><span class="math inline">\(\text{clip\_val}\)</span> is the clipping multiplier (<code>sampler.weight_clip = 10.0</code>) to avoid high-variance gradients from extremely rare combinations.</li>
</ul>
<p>For studies with no positive pathologies (“No Finding”), we assign a base weight:</p>
<p><span class="math display">\[w_j = \frac{p_{\text{target}}(\text{No Finding})}{p_{\text{dataset}}(\text{No Finding})}\]</span></p>
<p>Applying these weights at the batch-selection level forces the model to encounter rare pathology patterns during backpropagation without modifying the loss function, avoiding gradient-scale instabilities.</p>
<section id="ess-based-sampler-settings-v4" class="level3">
<h3 class="anchored" data-anchor-id="ess-based-sampler-settings-v4">6.1 ESS-Based Sampler Settings (v4)</h3>
<p>In the v4 training run, we configured the target prevalences <span class="math inline">\(p_{\text{target}}\)</span> in <code>params.yaml</code> directly using the class Effective Sample Size (ESS) metrics computed in <a href="#fig-ess" class="quarto-xref">Figure&nbsp;1 (c)</a>:</p>
<ol type="1">
<li><strong>Common Pathologies (ESS &gt; 250)</strong>: No correction needed. Target prevalences set to null, defaulting to raw dataset prevalence (e.g.&nbsp;Enlarged Cardiomediastinum, Cardiomegaly, Lung Opacity, No Finding).</li>
<li><strong>Moderate Pathologies (ESS 50–224)</strong>: Boosted to a 10% target prevalence (e.g.&nbsp;Atelectasis, Support Devices, Lung Lesion, Fracture, Pleural Effusion).</li>
<li><strong>Rare Pathologies (ESS &lt; 50)</strong>: Aggressively boosted to a 5% target prevalence (e.g.&nbsp;Pleural Other, Edema, Pneumonia, Consolidation, Pneumothorax).</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>ESS tier</th>
<th>Labels</th>
<th>Target prevalence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>High (ESS &gt; 250)</td>
<td>Enlarged Cardiomediastinum, Cardiomegaly, Lung Opacity, No Finding</td>
<td>Dataset prevalence (no change)</td>
</tr>
<tr class="even">
<td>Moderate (ESS 50–224)</td>
<td>Atelectasis, Support Devices, Lung Lesion, Fracture, Pleural Effusion</td>
<td>10%</td>
</tr>
<tr class="odd">
<td>Rare (ESS &lt; 50)</td>
<td>Pleural Other, Edema, Pneumonia, Consolidation, Pneumothorax</td>
<td>5%</td>
</tr>
</tbody>
</table>
<p>This structured up-weighting guarantees that the backpropagated gradients contain meaningful representations of rare clinical conditions, preventing the training loop from defaulting to the dominant “normal” mode.</p>


<!-- -->


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-chen2024chexagent" class="csl-entry" role="listitem">
Chen, Zhihong, Maya Varma, Justin Xu, Magdalini Paschali, Dave Van Veen, Andrew Johnston, Alaa Youssef, et al. 2024. <span>“A Vision-Language Foundation Model to Enhance Efficiency of Chest x-Ray Interpretation.”</span> <em>arXiv Preprint arXiv:2401.12208</em>, January. <a href="https://arxiv.org/abs/2401.12208">https://arxiv.org/abs/2401.12208</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/diegovillaba\.github\.io\/ReportCXR");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "2. Data Distribution &amp; Sampler Correction"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Diego Villalba (Applied Research Candidate)"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-06-26"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>::: {.non-technical-summary}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">##### Section Summary (Non-Technical)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>This section explains how we handle the huge imbalance in clinical data. Most X-rays are completely normal, meaning that an AI trained on this data would quickly learn to default to predicting "normal" to get easy high scores. We solve this by calculating mathematical weights for each study. When the AI trains, it is shown rare pathologies more frequently and normal X-rays less frequently. This forces the model to actually learn the signatures of rare diseases rather than taking lazy shortcuts.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Dataset Loading &amp; Integrity Audit</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>The Indiana University Chest X-ray (IU CXR) dataset consists of two raw CSV files:</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`indiana_reports.csv`** — 3,851 rows × 8 columns (<span class="in">`uid`</span>, <span class="in">`MeSH`</span>, <span class="in">`Problems`</span>, <span class="in">`image`</span>, <span class="in">`indication`</span>, <span class="in">`comparison`</span>, <span class="in">`findings`</span>, <span class="in">`impression`</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`indiana_projections.csv`** — 7,466 rows × 3 columns (<span class="in">`uid`</span>, <span class="in">`filename`</span>, <span class="in">`projection`</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>Each study (<span class="in">`uid`</span>) links to one or two image projections. Reports and projections are joined on <span class="in">`uid`</span> to produce a per-study dataframe (one row per study, with <span class="in">`frontal`</span> and <span class="in">`lateral`</span> image lists as columns).</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1.1 Projection Coverage</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Projections per study <span class="pp">|</span> Studies <span class="pp">|</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 446 <span class="pp">|</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 3,210 <span class="pp">|</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> 181 <span class="pp">|</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 13 <span class="pp">|</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>Of the 3,851 studies: **3,689 have at least one frontal image** and **3,550 have a lateral image**. The 162 studies lacking a frontal view are still retained in the join — the model always receives the frontal image at training time; if unavailable, the study is skipped.</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1.2 Null Counts in Raw Reports</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Column <span class="pp">|</span> Missing <span class="pp">|</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`indication`</span> <span class="pp">|</span> 86 <span class="pp">|</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`comparison`</span> <span class="pp">|</span> 1,166 <span class="pp">|</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`findings`</span> <span class="pp">|</span> 514 <span class="pp">|</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`impression`</span> <span class="pp">|</span> 31 <span class="pp">|</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1.3 Usable Study Count</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>Studies without a <span class="in">`findings`</span> text cannot be used as generation targets and are dropped:</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>$$N_{\text{raw}} = 3{,}851 \xrightarrow{\text{drop empty findings}} N_{\text{usable}} = 3{,}337$$</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>This **3,337-study corpus** is the basis for all subsequent analysis, CheXbert labeling, and the train/test split.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. CheXbert Labeling</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>Each study's <span class="in">`findings`</span> text is passed through **CheXbert** <span class="co">[</span><span class="ot">@chen2024chexagent</span><span class="co">]</span>, a BERT-based classifier that extracts a 14-dimensional binary label vector. The <span class="in">`uncertain_policy`</span> is set to <span class="in">`positive`</span> (uncertain mentions are treated as present).</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Results are cached to <span class="in">`data/processed/chexbert_labels.parquet`</span> after the first run (~10–20 min on CPU).</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.1 Positive Counts per Label</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Label <span class="pp">|</span> Positive studies <span class="pp">|</span> Prevalence <span class="pp">|</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> No Finding <span class="pp">|</span> 1,293 <span class="pp">|</span> **38.7%** <span class="pp">|</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Opacity <span class="pp">|</span> 450 <span class="pp">|</span> 13.5% <span class="pp">|</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cardiomegaly <span class="pp">|</span> 414 <span class="pp">|</span> 12.4% <span class="pp">|</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Enlarged Cardiomediastinum <span class="pp">|</span> 249 <span class="pp">|</span> 7.5% <span class="pp">|</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Atelectasis <span class="pp">|</span> 224 <span class="pp">|</span> 6.7% <span class="pp">|</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Support Devices <span class="pp">|</span> 153 <span class="pp">|</span> 4.6% <span class="pp">|</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Lesion <span class="pp">|</span> 134 <span class="pp">|</span> 4.0% <span class="pp">|</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Fracture <span class="pp">|</span> 121 <span class="pp">|</span> 3.6% <span class="pp">|</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pleural Effusion <span class="pp">|</span> 105 <span class="pp">|</span> 3.1% <span class="pp">|</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pleural Other <span class="pp">|</span> 49 <span class="pp">|</span> 1.5% <span class="pp">|</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Edema <span class="pp">|</span> 44 <span class="pp">|</span> 1.3% <span class="pp">|</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pneumonia <span class="pp">|</span> 30 <span class="pp">|</span> 0.9% <span class="pp">|</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Consolidation <span class="pp">|</span> 25 <span class="pp">|</span> 0.7% <span class="pp">|</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pneumothorax <span class="pp">|</span> 17 <span class="pp">|</span> 0.5% <span class="pp">|</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Dataset Distribution &amp; Concentration</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>::: {#fig-dataset-dist layout="[<span class="co">[</span><span class="ot">1, 1</span><span class="co">]</span>, <span class="co">[</span><span class="ot">1</span><span class="co">]</span>]"}</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="al">![Label Prevalences in the IU CXR Dataset](../reports/figures/label_prevalences.png)</span>{#fig-prevalences}</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="al">![Pathology Co-occurrence Matrix](../reports/figures/cooccurrence_matrix.png)</span>{#fig-cooccurrence}</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="al">![Effective Sample Size (ESS) per Clinical Label](../reports/figures/class_ess.png)</span>{#fig-ess}</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>Clinical data distributions and label statistics.</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>The severe class imbalance is illustrated in @fig-prevalences and @fig-cooccurrence. Nine of the 14 labels have prevalence below 5% (highlighted in red in @fig-prevalences).</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.1 Dataset Concentration Metrics</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>To quantify how unequally the label mass is distributed, we compute Shannon entropy and effective number of labels:</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>$$H = -\sum_{l} \hat{p}_l \log \hat{p}_l = 2.005 \text{ nats}$$</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>$$K_{\text{eff}} = e^H = 7.42 \quad (\text{out of 14})$$</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>A uniform 14-label distribution would give $K_{\text{eff}} = 14$. A value of **7.42** means the dataset behaves as if only ~7 labels exist at equal prevalence — the remaining label mass is dominated by <span class="in">`No Finding`</span>, <span class="in">`Lung Opacity`</span>, and <span class="in">`Cardiomegaly`</span>.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.2 Tail Mass</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>We define the "tail" as studies whose only positive labels have prevalence &lt; 5%. These studies carry signal for the rarest pathologies but receive almost no gradient under uniform sampling:</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>$$\text{Tail mass} = 8.2\% \approx 274 \text{ studies}$$</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>These 274 studies are the ones the importance-weighted sampler is most critical for — they are the first to be de-prioritized under uniform sampling.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Hierarchical Clustering &amp; Label Associations</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>To understand how clinical findings co-occur and group together, we performed hierarchical agglomerative clustering on the binary CheXbert label vectors from the training set.</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.1 Hierarchical Agglomerative Clustering Implementation</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Each label $l \in L$ is represented as a boolean occurrence vector $v_l \in <span class="sc">\{</span>0, 1<span class="sc">\}</span>^N$ over the $N = 3{,}337$ studies. We define the pairwise distance between label occurrence vectors using the Jaccard distance metric to measure the relative co-occurrence similarity:</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>$$d(A, B) = 1 - \frac{|A \cap B|}{|A \cup B|} = 1 - \frac{\sum_{i=1}^N (L_{i, A} \wedge L_{i, B})}{\sum_{i=1}^N (L_{i, A} \vee L_{i, B})}$$</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>The condensed distance matrix was computed via SciPy's <span class="in">`pdist`</span>. We then performed agglomerative clustering via the average linkage method:</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>$$d(u, v) = \sum_{i \in u, j \in v} \frac{d(i, j)}{|u||v|}$$</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>The clustering tree was visualized as a dendrogram (see @fig-dendrogram), with the cluster color threshold set at $0.7 \times \max(Z<span class="co">[</span><span class="ot">:, 2</span><span class="co">]</span>)$ to group labels into distinct clinical families.</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>::: {#fig-clustering-results layout="<span class="co">[</span><span class="ot">1, 1</span><span class="co">]</span>"}</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="al">![Label Hierarchical Clustering Dendrogram](../reports/figures/label_dendrogram.png)</span>{#fig-dendrogram}</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="al">![Pairwise Association Rules Heatmap](../reports/figures/assoc_rules_heatmap.png)</span>{#fig-assoc-heatmap}</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>Clustering and co-occurrence analysis.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>The dendrogram in @fig-dendrogram reveals distinct clinical syndromes that align with medical logic:</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Cardiac Cluster**: Cardiomegaly, Edema, and Enlarged Cardiomediastinum group closely together, reflecting congestive heart failure progression.</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Infection/Airspace Cluster**: Pneumonia and Consolidation form a tight cluster, indicating airspace disease.</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Pleural Cluster**: Pleural Effusion and Pleural Other group together, showing pleural space pathology.</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.2 Top Conditional Co-occurrence Pairs</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>Before mining directional rules, the raw conditional co-occurrence matrix surfaces the strongest pairwise associations:</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Given (row) <span class="pp">|</span> Then (column) <span class="pp">|</span> P(col <span class="sc">\|</span> row) <span class="pp">|</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Opacity <span class="pp">|</span> Pneumonia <span class="pp">|</span> 0.633 <span class="pp">|</span></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cardiomegaly <span class="pp">|</span> Edema <span class="pp">|</span> 0.614 <span class="pp">|</span></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Opacity <span class="pp">|</span> Atelectasis <span class="pp">|</span> 0.540 <span class="pp">|</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Opacity <span class="pp">|</span> Consolidation <span class="pp">|</span> 0.520 <span class="pp">|</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Opacity <span class="pp">|</span> Pleural Effusion <span class="pp">|</span> 0.448 <span class="pp">|</span></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Opacity <span class="pp">|</span> Edema <span class="pp">|</span> 0.386 <span class="pp">|</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lung Opacity <span class="pp">|</span> Pleural Other <span class="pp">|</span> 0.367 <span class="pp">|</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cardiomegaly <span class="pp">|</span> Pleural Effusion <span class="pp">|</span> 0.333 <span class="pp">|</span></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cardiomegaly <span class="pp">|</span> Enlarged Cardiomediastinum <span class="pp">|</span> 0.297 <span class="pp">|</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Pleural Effusion <span class="pp">|</span> Edema <span class="pp">|</span> 0.295 <span class="pp">|</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Association Rules Mining</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>This co-occurrence structure confirms that X-ray findings do not occur independently. To mine directional relationships between findings, we implemented association rules mining over the binary label matrix. <span class="in">`No Finding`</span> is excluded from all rule mining — it is a logical complement label, not a pathology. This yields 90 directional candidate rules across 13 pathology labels.</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>For each candidate pair of pathologies $A \rightarrow B$, we compute:</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Support**: The joint prevalence of both findings in the dataset:</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>   $$\text{Support}(A \rightarrow B) = P(A \wedge B) = \frac{\sum_{i=1}^N L_{i, A} L_{i, B}}{N}$$</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Confidence**: The conditional probability of consequent $B$ given antecedent $A$:</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>   $$\text{Confidence}(A \rightarrow B) = P(B \mid A) = \frac{P(A \wedge B)}{P(A)} = \frac{\sum_{i=1}^N L_{i, A} L_{i, B}}{\sum_{i=1}^N L_{i, A}}$$</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Lift**: The ratio of confidence to the baseline prevalence of $B$. A lift greater than 1.0 indicates a positive clinical co-occurrence beyond random chance:</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>   $$\text{Lift}(A \rightarrow B) = \frac{P(B \mid A)}{P(B)} = \frac{N \sum_{i=1}^N L_{i, A} L_{i, B}}{\left(\sum_{i=1}^N L_{i, A}\right) \left(\sum_{i=1}^N L_{i, B}\right)}$$</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>We mined **90 total directional rules** across 13 pathology labels (excluding `No Finding`). Filtering at **confidence $\ge 0.25$** and **lift $\ge 1.5$** yields **12 clinically significant rules**:</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Antecedent ($A$) <span class="pp">|</span> Consequent ($B$) <span class="pp">|</span> Support <span class="pp">|</span> Confidence <span class="pp">|</span> Lift <span class="pp">|</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Edema** <span class="pp">|</span> Pleural Effusion <span class="pp">|</span> $0.0039$ <span class="pp">|</span> $0.2955$ <span class="pp">|</span> $9.3898$ <span class="pp">|</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Edema** <span class="pp">|</span> Cardiomegaly <span class="pp">|</span> $0.0081$ <span class="pp">|</span> $0.6136$ <span class="pp">|</span> $4.9461$ <span class="pp">|</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Atelectasis** <span class="pp">|</span> Lung Opacity <span class="pp">|</span> $0.0363$ <span class="pp">|</span> $0.5402$ <span class="pp">|</span> $4.0057$ <span class="pp">|</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Lung Opacity** <span class="pp">|</span> Atelectasis <span class="pp">|</span> $0.0363$ <span class="pp">|</span> $0.2689$ <span class="pp">|</span> $4.0057$ <span class="pp">|</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Pleural Effusion** <span class="pp">|</span> Lung Opacity <span class="pp">|</span> $0.0141$ <span class="pp">|</span> $0.4476$ <span class="pp">|</span> $3.3193$ <span class="pp">|</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Edema** <span class="pp">|</span> Lung Opacity <span class="pp">|</span> $0.0051$ <span class="pp">|</span> $0.3864$ <span class="pp">|</span> $2.8651$ <span class="pp">|</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Pleural Other** <span class="pp">|</span> Lung Opacity <span class="pp">|</span> $0.0054$ <span class="pp">|</span> $0.3673$ <span class="pp">|</span> $2.7241$ <span class="pp">|</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Pleural Effusion** <span class="pp">|</span> Cardiomegaly <span class="pp">|</span> $0.0105$ <span class="pp">|</span> $0.3333$ <span class="pp">|</span> $2.6868$ <span class="pp">|</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Enlarged Cardiomediastinum** <span class="pp">|</span> Cardiomegaly <span class="pp">|</span> $0.0222$ <span class="pp">|</span> $0.2972$ <span class="pp">|</span> $2.3955$ <span class="pp">|</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Pleural Other** <span class="pp">|</span> Cardiomegaly <span class="pp">|</span> $0.0039$ <span class="pp">|</span> $0.2653$ <span class="pp">|</span> $2.1385$ <span class="pp">|</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Enlarged Cardiomediastinum** <span class="pp">|</span> Lung Opacity <span class="pp">|</span> $0.0198$ <span class="pp">|</span> $0.2651$ <span class="pp">|</span> $1.9656$ <span class="pp">|</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Support Devices** <span class="pp">|</span> Lung Opacity <span class="pp">|</span> $0.0117$ <span class="pp">|</span> $0.2549$ <span class="pp">|</span> $1.8902$ <span class="pp">|</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>These 12 rules (visualized in @fig-assoc-heatmap) represent highly strong, non-trivial clinical dependencies. For example: Edema has a 61.4% conditional probability of co-occurring with Cardiomegaly ($\text{lift}=4.95$), and is 9.39× more likely to co-occur with Pleural Effusion than a study drawn at random.</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>**EDA vs. inference thresholds**: The EDA strong-rules table above uses lift ≥ 1.5 for display purposes. The runtime inference conditioner in Section 5 uses a slightly more permissive lift ≥ 1.2 threshold to maximize recall of rare associations at inference time. All 12 rules above also satisfy the inference threshold.</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>This motivates injecting these conditional probabilities into the prompting pipeline at test time: if a clinical indication triggers antecedent $A$, we supply the conditional probability of consequent $B$ as a soft prior context hint (see <span class="co">[</span><span class="ot">Section 5 — Inference Conditioning</span><span class="co">](05_inference_conditioning.qmd)</span>).</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6. Importance Sampling &amp; Sampler Correction</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>To prevent the model from collapsing to the majority class and simply predicting "normal" for all patients, we implement a <span class="in">`WeightedRandomSampler`</span>. For each study $j$, we compute an importance weight $w_j$ based on the target prevalences specified in <span class="in">`params.yaml`</span>:</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>$$w_j = \text{clip}\left( \left( \prod_{l \in L_j} \frac{p_{\text{target}}(l)}{p_{\text{dataset}}(l)} \right)^{\frac{1}{|L_j|}}, \text{clip<span class="sc">\_</span>val} \right)$$</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>Where:</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$L_j$ is the set of positive pathologies present in study $j$.</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$p_{\text{target}}(l)$ is the user-specified target prevalence for pathology $l$.</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$p_{\text{dataset}}(l)$ is the empirical prevalence of pathology $l$ in the training set.</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="ss">*   </span>$\text{clip<span class="sc">\_</span>val}$ is the clipping multiplier (<span class="in">`sampler.weight_clip = 10.0`</span>) to avoid high-variance gradients from extremely rare combinations.</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>For studies with no positive pathologies ("No Finding"), we assign a base weight:</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>$$w_j = \frac{p_{\text{target}}(\text{No Finding})}{p_{\text{dataset}}(\text{No Finding})}$$</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>Applying these weights at the batch-selection level forces the model to encounter rare pathology patterns during backpropagation without modifying the loss function, avoiding gradient-scale instabilities.</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="fu">### 6.1 ESS-Based Sampler Settings (v4)</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>In the v4 training run, we configured the target prevalences $p_{\text{target}}$ in <span class="in">`params.yaml`</span> directly using the class Effective Sample Size (ESS) metrics computed in @fig-ess:</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Common Pathologies (ESS &gt; 250)**: No correction needed. Target prevalences set to null, defaulting to raw dataset prevalence (e.g. Enlarged Cardiomediastinum, Cardiomegaly, Lung Opacity, No Finding).</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Moderate Pathologies (ESS 50–224)**: Boosted to a 10% target prevalence (e.g. Atelectasis, Support Devices, Lung Lesion, Fracture, Pleural Effusion).</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Rare Pathologies (ESS &lt; 50)**: Aggressively boosted to a 5% target prevalence (e.g. Pleural Other, Edema, Pneumonia, Consolidation, Pneumothorax).</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ESS tier <span class="pp">|</span> Labels <span class="pp">|</span> Target prevalence <span class="pp">|</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> High (ESS &gt; 250) <span class="pp">|</span> Enlarged Cardiomediastinum, Cardiomegaly, Lung Opacity, No Finding <span class="pp">|</span> Dataset prevalence (no change) <span class="pp">|</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Moderate (ESS 50–224) <span class="pp">|</span> Atelectasis, Support Devices, Lung Lesion, Fracture, Pleural Effusion <span class="pp">|</span> 10% <span class="pp">|</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rare (ESS &lt; 50) <span class="pp">|</span> Pleural Other, Edema, Pneumonia, Consolidation, Pneumothorax <span class="pp">|</span> 5% <span class="pp">|</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>This structured up-weighting guarantees that the backpropagated gradients contain meaningful representations of rare clinical conditions, preventing the training loop from defaulting to the dominant "normal" mode.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>ReportCXR Technical Challenge</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>